// LOCALHOST
### Get all movies
GET http://localhost:3000/movies

### Get movie by id
GET http://localhost:3000/movies/679306f4250adad0e2a85bd9

### Create movie
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title":"The Avengers",
    "director": "Joss Whedon",
    "release": "April 11, 2012",
    "duration": "143 minutes",
    "genre": "Action" 
}

### Update movie by id
PUT http://localhost:3000/movies
Content-Type: application/json

{
    "title":"The Avengers",
    "director": "Joss Whedon",
    "release": "April 11, 2012",
    "duration": "143 minutes",
    "genre": "Action" 
}

### Delete contact by id
DELETE http://localhost:3000/movies

//----------------------------------------

### Get all actors
GET http://localhost:3000/actors

### Create actor
POST http://localhost:3000/actors
Content-Type: application/json

{
    "name": "Brad Pitt",
    "birth": "December 18, 1963",
    "nationality": "American",
    "filmography": ["Fight Club", "Once Upon a Time in Hollywood"]
}
